POWER_ON = 1
POWER_UKNOWN = 0
POWER_OFF = -1

MONDAY = 'MONDAY'
TUESDAY = 'TUESDAY'
WEDNESDAY = 'WEDNESDAY'
THURSDAY = 'THURSDAY'
FRIDAY = 'FRIDAY'
SATURDAY = 'SATURDAY'
SUNDAY = 'SUNDAY'

WEEKDAYS = (
    'MONDAY',
    'TUESDAY',
    'WEDNESDAY',
    'THURSDAY',
    'FRIDAY',
    'SATURDAY',
    'SUNDAY'
)
SCHEDULES_FILE_PATH = 'groups.xlsx'

START = 'START'
FINISH = 'FINISH'

GROUP_NAMES = ('1.1', '1.2', '2.1', '2.2', '3.1', '3.2')
